修正

diff --git a/.github/workflows/reservation.yml b/.github/workflows/reservation.yml
--- a/.github/workflows/reservation.yml
+++ b/.github/workflows/reservation.yml
@@ -178,21 +178,25 @@ jobs:
           curl -X PATCH \
             -H 'Content-Type: application/json' \
             -H "Authorization: Bearer ${{ secrets.CRON_JOB_TOKEN }}" \
-            -d "{
+            -d '{
               "job": {
                 "enabled": true,
                 "schedule": {
-                  "hours": [$hour],
-                  "mdays": [$day],
-                  "minutes": [$minutes],
-                  "months": [$month]
+                  "hours": ['$hour'],
+                  "mdays": ['$day'],
+                  "minutes": ['$minutes'],
+                  "months": ['$month']
                 },
                 "extendedData": {
                   "body": "{\"event_type\": \"active\", \"inputs\": {\"repository\": \"${{ inputs.repository }}\", \"repository_no_register\": \"${{ inputs.repository_no_register }}\", \"target\": \"${{ inputs.target }}\", \"sync\": \"${{ inputs.sync }}\"}}"
-                },
+                }
               }
-            }" \
-            https://api.cron-job.org/jobs/${{ env.job_id }} || { echo 'Failed to register CronJob'; echo "エラーログ: $(curl -X PATCH -H 'Content-Type: application/json' -H "Authorization: Bearer ${{ secrets.CRON_JOB_TOKEN }}" -d '{\"job\": {\"enabled\": true, \"schedule\": {\"hours\": [$hour], \"mdays\": [$day], \"minutes\": [$minutes], \"months\": [$month]}}}' https://api.cron-job.org/jobs/${{ env.job_id }})"; exit 1; }
+            }' \
+            https://api.cron-job.org/jobs/${{ env.job_id }} ||
+            {
+              echo 'Failed to register CronJob'; echo "エラーログ: $(curl -X PATCH -H 'Content-Type: application/json' -H "Authorization: Bearer ${{ secrets.CRON_JOB_TOKEN }}" -d '{\"job\": {\"enabled\": true, \"schedule\": {\"hours\": [$hour], \"mdays\": [$day], \"minutes\": [$minutes], \"months\": [$month]}}}' https://api.cron-job.org/jobs/${{ env.job_id }})"; exit 1; }
+            }
+
 
       - name: CronJobリストを取得
         run: |
